school_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic.base import TemplateView

from dashboards.views import search_by_major, search_by_company, search_by_name, graduation_rate, studend_per_industry_rate, student_rate_by_major, salary_rate_by_major

urlpatterns = [
    # Examples:
    # url(r'^$', 'school_demo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'', include('users.urls')),
    url(r'^major-search', search_by_major, name='major-search'),
    url(r'^company-search', search_by_company, name='company-search'),
    url(r'^name-search', search_by_name, name='name-search'),
    url(r'^graduation-rate/', graduation_rate, name='graduation-rate'),
    url(r'^industry-rate/', studend_per_industry_rate, name='industry-rate'),
    url(r'^major-rate/', student_rate_by_major, name='major-rate'),
    url(r'^salary-rate/', salary_rate_by_major, name='salary-rate'),
    url(r'^faq', TemplateView.as_view(template_name='faq.html'), name='faq')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import sign_up, sign_in, ProfileCreateView, DashboardView, CareerView, AdminProfileView, show_profile

urlpatterns = [
    url(r'^signup/', sign_up, name='signup'),
    url(r'^login/', sign_in, name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='logged_out.html'), name='logout'),
    url(r'^dashboard', DashboardView.as_view(template_name='dashboard.html'), name='dashboard'),
    url(r'^profile/add-career', CareerView.as_view(), name='add-career'),
    url(r'^profile/admin', AdminProfileView.as_view(), name='admin-profile'),
    url(r'^profile/edit', ProfileCreateView.as_view(), name='profile'),
    url(r'^profile', show_profile, name='show-profile')
]

dashboards/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import User
from django.db import models

from .utils import validate_phone_number

ROLE_CHOICES = (
    ('0', 'Admin'),
    ('1', 'General user')
)

GENDER_CHOICES = (
    ('0', 'Male'),
    ('1', 'Female')
)

DEGREE_CHOICES = (
    ('0', 'MS'),
    ('1', 'MBA'),
    ('2', 'BBA')
)

class CustomUser(User):
    role = models.CharField(
        max_length=2,
        choices=ROLE_CHOICES,
        default=1,
    )
    middle_name = models.CharField(max_length=100, blank=True, null=True)

class Major(models.Model):
    major_name = models.CharField(max_length=100)

    def __str__(self):
        return self.major_name

SALARY_RANGE_CHOICES = (
    ('1', '50,000 to 60,000'),
    ('2', '60,000 to 70,000'),
    ('3','70,000 to 80,000'),
    ('4', '80,000 to 90,000'),
    ('5', '90,000 to 100,000')
)

ENROLLEMENT_STATUS_CHOICES = (
    ('0', 'Full-time'),
    ('1', 'Intern')
)

class Company(models.Model):
    company_name = models.CharField(max_length=100)
    company_website = models.CharField(max_length=100)
    industry_type = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20,
                                    validators=[validate_phone_number])
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.company_name

class StudentCareer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True )
    job_role = models.CharField(max_length=100, blank=True, null=True)
    employment_start_date = models.DateField(blank=True, null=True)
    employment_end_date = models.DateField(blank=True, null=True)
    enrollment_status = models.CharField(
        max_length=2,
        choices=ENROLLEMENT_STATUS_CHOICES,
        blank=True, null=True
    )
    salary_range = models.CharField(
        max_length=5,
        choices=SALARY_RANGE_CHOICES,
    blank = True, null = True
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
                             blank=True, null=True)

class StudentProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=20,
                                    validators=[validate_phone_number])

    major1 = models.ForeignKey(Major, related_name='major1',
                               on_delete=models.CASCADE)
    major2 = models.ForeignKey(Major, related_name='major2',
                               on_delete=models.CASCADE, blank=True, null=True)
    degree_type = models.CharField(
        max_length=2,
        choices=DEGREE_CHOICES
    )
    graduation_date = models.DateField()

class AdminProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=20,
                                    validators=[validate_phone_number])
    # admin_title = models.CharField(max_length=200)

dashboards/forms.py
from django import forms

from users.models import Major

def get_majors_list():
    query = [(i.pk, i.major_name) for i in Major.objects.all()]
    return query

class SearchByMajorForm(forms.Form):
    major = forms.ChoiceField(choices=get_majors_list)

class SearchByInputForm(forms.Form):
    input = forms.CharField()

dashboards/views.py
import io
from collections import Counter
from datetime import timedelta, datetime

import matplotlib
matplotlib.use('Agg')
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from pylab import figure, axes, pie, title

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .forms import SearchByMajorForm, SearchByInputForm
from users.models import StudentCareer, StudentProfile, Major, Company, CustomUser


def search_by_major(request):
    context = {}

    if request.method == 'POST':
        form = SearchByMajorForm(request.POST)
        if form.is_valid():
            major = form.cleaned_data['major']
            major = Major.objects.get(pk=major)
            m1 = StudentProfile.objects.filter(major1=major)
            m2 = StudentProfile.objects.filter(major2=major)

            careers = []
            for i in m1:
                careers.append(StudentCareer.objects.filter(user=i.user))

            for i in m2:
                careers.append(StudentCareer.objects.filter(user=i.user))

            context['queryset'] = careers
    else:
        form = SearchByMajorForm()
        context['init'] = True

    context['form'] = form

    return render(request, 'search.html', context)

def search_by_company(request):
    context = {}

    if request.method == 'POST':
        form = SearchByInputForm(request.POST)
        if form.is_valid():
            company_name = form.cleaned_data['input'].lower().capitalize()
            companies = Company.objects.filter(company_name=company_name)

            queryset = []
            for company in companies:
                queryset.append(StudentCareer.objects.filter(company=company.pk))

            context['queryset'] = queryset
            context['current_date'] = datetime.today()
    else:
        form = SearchByInputForm()
        context['init'] = True

    context['form'] = form

    return render(request, 'company-search.html', context)

def search_by_name(request):
    context = {}

    if request.method == 'POST':
        form = SearchByInputForm(request.POST)
        if form.is_valid():
            names = form.cleaned_data['input'].capitalize()
            users = [
                (user.first_name, user.middle_name, user.last_name, str(user.pk))
                     for user in CustomUser.objects.filter(role='1')]
            result = []

            for user in users:
                if names in user:
                    result.append(user[-1])
            queryset = []
            for pk in result:
                try:
                    queryset.append(StudentCareer.objects.filter(user=int(pk)).order_by('employment_start_date')[0])
                except:
                    pass
            print(queryset)
            context['queryset'] = queryset
    else:
        form = SearchByInputForm()
        context['init'] = True

    context['form'] = form

    return render(request, 'name-search.html', context)

def graduation_rate(request):
    students = CustomUser.objects.filter(role='1')
    count = 0

    for student in students:
        try:
            gr_date = student.studentprofile.graduation_date
        except:
            pass
        else:
            emp_date = StudentCareer.objects.filter(
                user=student).order_by('employment_start_date')
            if emp_date:
                first_emp_date = emp_date[0].employment_start_date

                if gr_date + timedelta(days=6 * 30) >= first_emp_date:
                    count += 1

    res = count/(len(students)/100)

    f = figure(figsize=(6,6))

    ax = axes([0.1, 0.1, 0.8, 0.8])
    labels = 'Within 6 months', 'Over 6 months'
    fracs = [res, (100-res) ]
    explode=(0, 0.05)
    pie(fracs, explode=explode, labels=labels, autopct='%1.1f%%')
    title(
        'Percentage of students who got jobs within 6 months of graduation',
        bbox={'facecolor':'0.9', 'pad':5})

    # FigureCanvasAgg(f)
    buf = io.BytesIO()
    plt.savefig(buf, format='pdf')
    plt.close(f)
    response = HttpResponse(buf.getvalue(), content_type='application/pdf')
    return response

def studend_per_industry_rate(request):
    students = CustomUser.objects.filter(role='1')

    industry_list = []
    for student in students:
        try:
            industry = StudentCareer.objects.filter(
                user=student).order_by(
                'employment_start_date')[0].company.industry_type
        except IndexError:
            pass
        else:
            industry_list.append(industry)

    labels = []
    fracs = []

    working_students = len(industry_list)
    industries = set(industry_list)
    counter = Counter(industry_list)

    for industry in industries:
        percent = counter[industry]/(working_students/100)
        fracs.append(percent)
        labels.append(industry)

    f = figure(figsize=(6, 6))

    axes([0.1, 0.1, 0.8, 0.8])
    explode = [0 for i in range(len(industries))]
    explode[1] = 0.05
    pie(fracs, explode=explode, labels=labels, autopct='%1.1f%%', radius=0.8)
    title('Percentage of students employed in each industry', bbox={'facecolor': '0.8', 'pad': 5})

    # FigureCanvasAgg(f)
    buf = io.BytesIO()
    plt.savefig(buf, format='pdf')
    plt.close(f)
    response = HttpResponse(buf.getvalue(), content_type='application/pdf')
    return response

def salary_rate_by_major(request):
    majors = Major.objects.all()
    res = {}
    salary_range = {
        '1':'50,000 to 60,000',
        '2':'60,000 to 70,000',
        '3':'70,000 to 80,000',
        '4':'80,000 to 90,000',
        '5':'90,000 to 100,000'
    }

    with PdfPages(
            '/home/TeachYourself/teachyourself.pythonanywhere.com/users/static/files/salary_rate_by_major.pdf') as pdf:  # /home/TeachYourself/teachyourself.pythonanywhere.com/
        for major in majors:
            print(major)
            res[major] = []
            profiles = StudentProfile.objects.filter(major1=major)
            if profiles:
                for profile in profiles:
                    careers = StudentCareer.objects.filter(user=profile.user)
                    if careers:
                        current_salary_range = careers.order_by('employment_start_date')[0].salary_range
                        res[major].append(current_salary_range)

                    res[major].append(current_salary_range)
                labels = []
                fracs = []
                counter = Counter(res[major])
                print(counter)

                for salary in set(res[major]):
                    percent = counter[salary] / (len(res[major]) / 100)
                    fracs.append(percent)
                    labels.append(salary_range[salary])

                figure(figsize=(6, 6))

                ax = axes([0.1, 0.1, 0.8, 0.8])
                explode = [0 for _ in range(len(labels))]
                try:
                    explode[0] = 0.05
                except IndexError:
                    pass
                pie(fracs, explode=explode, labels=labels, autopct='%1.1f%%',
                    radius=0.8)
                title('Salary rate by major: ' + major.major_name,
                      bbox={'facecolor': '0.8', 'pad': 5})
                plt.gcf().subplots_adjust(bottom=0.15)
                pdf.savefig()  # saves the current figure into a pdf page
                plt.close()

        # We can also set the file's metadata via the PdfPages object:
        d = pdf.infodict()
        d['Title'] = 'Salary range by major'

    return HttpResponseRedirect('/static/files/salary_rate_by_major.pdf')

def student_rate_by_major(request):
    students = CustomUser.objects.filter(role='1')

    majors = []
    for student in students:
        try:
            major1 = StudentProfile.objects.get(user=student).major1
            major2 = StudentProfile.objects.get(user=student).major2
        except StudentProfile.DoesNotExist:
            pass
        else:
            majors.append(major1)
            if major2:
                majors.append(major2)

    counter = Counter(majors)

    labels = []
    fracs = []

    for major in set(majors):
        percent = counter[major] / (len(majors) / 100)
        fracs.append(percent)
        labels.append(major)

    f = figure(figsize=(6, 6))

    ax = axes([0.1, 0.1, 0.8, 0.8])
    explode = [0 for _ in range(len(labels))]
    explode[2] = 0.05
    pie(fracs, explode=explode, labels=labels, autopct='%1.1f%%', radius=0.7)
    title('Student per industry rate', bbox={'facecolor': '0.8', 'pad': 5})

    # FigureCanvasAgg(f)
    buf = io.BytesIO()
    plt.savefig(buf, format='pdf')
    plt.close(f)
    response = HttpResponse(buf.getvalue(), content_type='application/pdf')
    return response

users/templates/add-career.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="container-form">
        <div class="container-form-title"> Fill in career info</div>
        <form class="container-form-body" method="post" action="">
        {% csrf_token %}
            <table>{{ form.as_table }}</table>
        <button class="btn" type="submit">Save</button>
        </form>
    </div>
</div>
{%endblock%}

users/templates/base.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<header>
    <div class="header-navbar navbar">
        <div><a class="logo" href="{% url 'dashboard' %}">WeConnect</a></div>
        {% if user.is_authenticated %}
        <div class="navbar-item">Profile
        <div class="submenu">
            <div class="submenu-item"><a href="{% url 'show-profile' %}">View</a></div>
        <div class="submenu-item"><a href="{% if user.is_superuser %}{% url 'admin-profile' %}{%else%}{% url 'profile' %}{% endif %}">Edit</a></div>
        </div>
        </div>
        {% if user.is_superuser %}
        <div class="navbar-item">Reports
        <div class="submenu">
            <div class="submenu-item"><a href="{% url 'graduation-rate' %}">Placement rate</a></div>
            <div class="submenu-item"><a href="{% url 'industry-rate' %}">Top Recruiting industries</a></div>
            <div class="submenu-item"><a href="{% url 'salary-rate' %}">Salary Estimates</a></div>
            <div class="submenu-item"><a href="{% url 'major-rate' %}">Popular majors-2018</a></div>
        </div>
        </div>
        {% endif %}
        <div class="navbar-item">Search
        <div class="submenu">
            <div class="submenu-item"><a href="{% url 'company-search' %}">By company</a></div>
            <div class="submenu-item"><a href="{% url 'name-search' %}">By name</a></div>
            <div class="submenu-item"><a href="{% url 'major-search' %}">By department</a></div>
        </div>
        </div>
        <div class="navbar-item">Settings
        <div class="submenu">
            <div class="submenu-item"><a href="{% url 'logout' %}">Logout</a></div>
            <div class="submenu-item"><a href="{% url 'faq' %}">FAQ</a> </div>
        </div></div>
        {% else %}
        <div class="non-auth">
        <div><a href="{% url 'login' %}">Log In</a></div>
        <div style="color: hsla(0,0%,100%,0.6);">or</div>
        <div><a href="{% url 'signup' %}">Sign Up</a> </div>
        </div>
        {% endif %}
    </div>
</header>
<body>
{% block content %}
{% endblock content%}
</body>

<footer></footer>
</html>

users/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

users/templates/faq.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
<div class="container-form" style="width:1000px;">
    <ul>
        <li>I. Did you know?</li>
        <ul>
            <li>a. Baruch College is ranked among the region's and nation's top
                colleges by U.S. News & World Report, Forbes, Princeton Review,
                and others. Our campus is within easy reach of Wall Street, Midtown,
                and the global headquarters of major companies and non-profit and
                cultural organizations, giving students unparalleled internship,
                career, and networking opportunities. The College's more than 18,000
                students, who speak more than 110 languages and trace their heritage
                to more than 170 countries, have been repeatedly named one of the
                most ethnically diverse student bodies in the United States.
            </li>
        </ul>
        <li>II. What makes Baruch different?</li>
        <ul>
            <li>a. Baruch College is a dynamic community of scholars and distinguished
                professionals who educate one of the most diverse student
                populations in the United States. The College dates back nearly
                170 years, to the founding in 1847 of the Free Academy, the first
                free public college in the nation, and has carried on a tradition
                of academic excellence, accessibility, and opportunity for students
                from every corner of New York City, the metropolitan region, and around the world.
            </li>
        </ul>
        <li>Some stats about Baruch:</li>
        <ul>
            <li>North Region</li>
            <li>
                #5
                #20
                #3
                #9
                #11
                "Top Public Schools" for third consecutive year
                Best Regional Universities
                Least Debt Class, of 2017
            </li>
            <li>
                Schools With the Most International Students</li>
            <li>
                Most Innovative Schools</li><li> Nationwide
                #40
                #62
                Nation’s Top Public Schools for Undergraduate Business Programs
            <li>Best Undergraduate Business Programs</li>
            <li>Business Insider</li>
             <li>   ✔
                Best MBA Programs Under $15,000 a Year
            </li>
        </ul>
    </ul>
</div>
    </div>
{% endblock %}

users/templates/logged_out.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="container-form">
        <div class="container-form-title"> Log out</div>
        <div class="form-footer-text">
        You were logged out. <a href="{% url 'login' %}">Log in</a> again.</div>
    </div>
</div>
{% endblock %}

users/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="container-form">
        <div class="container-form-title">Your Profile</div>
        <form class="container-form-body" method="post" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.first_name.label }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.middle_name.label }}</td>
                    <td>{{ form.middle_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.last_name.label }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.gender.label }}</td>
                    <td>{{ form.gender }}</td>
                </tr>
                <tr>
                    <td>{{ form.phone_number.label }}</td>
                    <td>{{ form.phone_number }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td>{{ form.email.errors }}</td>
                </tr>
                <tr>
                    <td>{{ form.email.label }}</td>
                    <td>{{ form.email }}</td>
                </tr>
                <tr>
                    <td>{{ form.major1.label }}</td>
                    <td>{{ form.major1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.major2.label }}</td>
                    <td>{{ form.major2 }}</td>
                </tr>
                <tr>
                    <td>{{ form.degree_type.label }}</td>
                    <td>{{ form.degree_type }}</td>
                </tr>
                <tr>
                    <td>{{ form.graduation_date.label }}</td>
                    <td>{{ form.graduation_date }}</td>
                </tr>
            </table>
            {% if not profile %}
            <button class="btn" type="submit">Add profile</button>
            {%else%}
            <button class="btn" type="submit">Edit profile</button>
            {% endif %}
        </form>
{% if not profile %}
<div class="form-footer">Please, fill in info to be able to add the career info.</div>
{% else %}
{% for career in careers %}
<div class="container-form">
    <div class="container-form-title"> Your Career</div>
    {% if invalid %}
    Incorrect username or password
    {% endif %}
    <div class="container-form-body">
        <table>
            <tr>
                <td>Company name: </td>
                <td>{{ career.company }}</td>
            </tr>
            <tr>
                <td>Job name: </td>
                <td>{{ career.job_role }}</td>
            </tr>
            <tr>
                <td>Employment start date: </td>
                <td>{{ career.employment_start_date }}</td>
            </tr>
            {% if career.employment_end_date %}
            <tr>
                <td>Employment end date: </td>
                <td>{{ career.employment_end_date }}</td>
            </tr>
            {% endif %}
            <tr>
                <td>Enrollment status: </td>
                <td>{{ career.get_enrollment_status_display }}</td>
            </tr>
                <tr>
                <td>Salary range: </td>
                <td>{{ career.get_salary_range_display }}</td>
            </tr>
        </table>
    </div>
</div>
{% endfor %}
    <div class="form-footer">
    {% if not user.is_superuser %}
    <a class="my-btn" href="{% url 'add-career' %}">Add career info</a>
    <a class="my-btn" href="{% url 'dashboard' %}">Go back to dashboard</a>
    {%endif%}
    {% endif %}
    </div>
{%endblock%}

users/templates/show-profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="container-form">
        <div class="container-form-title">Your Profile</div>
        <div class="container-form-body">
            {% if profile %}
            <table>
                <td> Name: </td>
                <td>{{ profile.user.first_name }} {{ profile.user.middle_name }} {{ profile.user.last_name }}</td>
                </tr>
                <tr>
                    <td>Gender:</td>
                    <td>{{ profile.get_gender_display }}</td>
                </tr>
                <tr>
                    <td>Phone number</td>
                    <td>{{ profile.phone_number }}</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{ profile.user.email }}</td>
                </tr>
                    {% if not user.is_superuser %}
                    <tr>
                        <td>Major:</td>
                        <td>{{ profile.major1}}</td>
                    </tr>
                        {% if profile.major2 %}
                        <tr>
                            <td>Major:</td>
                            <td>{{ profile.major2 }}</td>
                        </tr>
                        {% endif %}
                    <tr>
                        <td>Degree:</td>
                        <td>{{ profile.get_degree_type_display }}</td>
                    </tr>

                    <tr>
                        <td>Graduation_date:</td>
                        <td>{{ profile.graduation_date }}</td>
                    </tr>
                    {%endif%}
            </table>

        </div>

        {% else %}
        <div class="form-footer">You don't have the profile info.</div>
        {%endif%}
        {% for career in careers %}
<div class="container-form">
    <div class="container-form-title"> Your Career</div>
    <div class="container-form-body">
        <table>
            <tr>
                <td>Company name: </td>
                <td>{{ career.company }}</td>
            </tr>
            <tr>
                <td>Job name: </td>
                <td>{{ career.job_role }}</td>
            </tr>
            <tr>
                <td>Employment start date: </td>
                <td>{{ career.employment_start_date }}</td>
            </tr>
            {% if career.employment_end_date %}
            <tr>
                <td>Employment end date: </td>
                <td>{{ career.employment_end_date }}</td>
            </tr>
            {% endif %}
            <tr>
                <td>Enrollment status: </td>
                <td>{{ career.get_enrollment_status_display }}</td>
            </tr>
                <tr>
                <td>Salary range: </td>
                <td>{{ career.get_salary_range_display }}</td>
            </tr>
        </table>
    </div>
</div>
{% endfor %}

    <div class="form-footer">
    <a class="my-btn" href="{% if user.is_superuser %}{% url 'admin-profile' %}{%else%}{% url 'profile' %}{% endif %}">Edit profile</a>
    <a class="my-btn" href="{% url 'dashboard' %}">Go back to dashboard</a>
    </div>
{%endblock%}